blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ â€‹ Ask a question
    url: https://discord.gg/S8s75Yf
    about: Support for Carbon is provided on Discord. Instead of making an issue to ask a question, join us on discord and we'll be happy to help!
