# Sets the player's channel to the specified channel when they join
# Set to "" or remove to disable
# Set to DEFAULT to set the player's channel to the default channel on join
# Otherwise, set to a channel to set the player's channel to it on join
# For example, channel-on-join: "global" sets their channel to global on join
channel-on-join: ''

# Plays a sound and highlights the message when someone types your name
channel-pings:
  # If player names are case sensitive, if true you must type Player to ping Player, 'player' will not work
  case-sensitive: false
  # The way players will see the ping
  display: "<bold><red><ping></red><bold>"
  # Determines if this feature is enabled
  enabled: true
  # The text that pings must begin with. A prefix of '@' means you have to type '@Player' to ping Player
  prefix: '@'
  # The sound played to the pinged player
  sound:
    name: minecraft:entity.experience_orb.pickup
    pitch: 1
    source: PLAYER
    volume: 10
	
# Options: MOJANG, MINIMESSAGE_MARKDOWN, MINIMESSAGE, MINEDOWN
format-type: MINIMESSAGE

# The list of regex patterns to show items in chat. '\\Q' and '\\E' just denote that the content isn't regex.
item-link-patterns:
- "\\Q[item]\\E"

# Options: NONE, REDIS, BUNGEECORD
# 'BUNGEE' - Uses bungee plugin messaging, requires BungeeCord or another proxy which supports it (Velocity!)
# 'REDIS' - Uses redis for cross server syncing, does not require a server proxy
# 'NONE' - Do not sync anything cross server, this is the default
# Note: In order for channels to sync cross server, you'll need to enable is-cross-server for the
#   channel as well as this setting.
messaging-type: NONE

# The credentials necessary to connect to your redis server
redis-credentials:
  database: 0
  host: localhost
  password: ''
  port: 6379

# Used for <server> placeholder in formats
server-name: Server

# Set this to false to disable warnings and tips when the plugin thinks there may be configuration issues.
show-tips: true

# The prefix shown when spying on a user's message
spy-prefix: "<color>[SPY] "

# The credentials used to connect to your database. Requires storageType=MYSQL
sql-credentials:
  database: database
  host: host
  password: password
  port: 3306
  username: username

# Options: JSON, MYSQL
storage-type: JSON

# Various options relating to the /whisper command
whisper-options:
  cannot-ignore-message: "<red>You cannot ignore that channel!"
  cannot-use-message: You cannot use that channel!
  console-format: "<gold>[<white><sender> <gray>-> <white><receiver><gold>] <message>"
  log-to-console: true
  now-whispering-player: "<white>You are now whispering <green><player><white>!"
  pings:
    enabled: true
    sound:
      name: minecraft:entity.experience_orb.pickup
      pitch: 1
      source: PLAYER
      volume: 10
  receiver-format: "<gold>[<white><sender> <gray>-> <white>Me<gold>] <message>"
  receiver-toggled-off: "<red><receiver> <red>has whispers toggled off!"
  sender-format: "<gold>[<white>Me <gray>-> <white><receiver><gold>] <message>"
  sender-toggled-off: "<red>You have whispers toggled off!"
  switch-failure-message: "<red>You cannot use channel <channel>!"
  switch-message: "<gray>You are now in <color><channel> <gray>chat!"
  switch-other-message: "<gray><player> <reset><gray>is now in <color><channel> <gray>chat!"
  toggle-off-message: "<gray>You can no longer see <color><channel> <gray>chat!"
  toggle-on-message: "<gray>You can now see <color><channel> <gray>chat!"
  toggle-other-off-message: "<gray><player> <reset><gray>can no longer see <color><channel>
    <gray>chat!"
  toggle-other-on-message: "<gray><player> <reset><gray>can now see <color><channel>
    <gray>chat!"
